/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-09-07 05:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>방울방울</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("<style>\r\n");
      out.write(" @font-face {\r\n");
      out.write("    font-family: 'yg-jalnan';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("* {font-family:'@여기어때 잘난체'}\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("#page {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("\tpadding-bottom:30px;\r\n");
      out.write("\theight: 3300px;\r\n");
      out.write("}\r\n");
      out.write("#content {\r\n");
      out.write("\tmargin-top:none;\r\n");
      out.write("\tmargin-left:70px;\r\n");
      out.write("\tmargin-right:70px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 {\r\n");
      out.write(" \twidth:7%;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl2 {\r\n");
      out.write(" \twidth:7%;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-left: 1.3%;\r\n");
      out.write("\tmargin-right: 1.3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl3 {\r\n");
      out.write(" \twidth:7%;\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\tmargin: 25px;\r\n");
      out.write("\tpadding: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 img, #tbl2 img, #tbl3 img {\r\n");
      out.write("\t\twidth: 15%;\r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("#img1,#img2,#img5,#img8,#img11,#img14{\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#img-1,#img-2,#img-5,#img-8,#img-11{\r\n");
      out.write("\tdisplay:none;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#img13,#img14{\r\n");
      out.write("\tmargin:0px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image{\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("\twidth: 15.5%;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin:2%;\r\n");
      out.write("\tfont-size:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image img {\r\n");
      out.write("\twidth: 180px;\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("   font-size: 50px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   margin-top:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 img,#tbl2 img,#tbl3 img{\r\n");
      out.write("\twidth:550px;\r\n");
      out.write("}\r\n");
      out.write("#img3{\r\n");
      out.write("\theight:280px;\r\n");
      out.write("}\r\n");
      out.write("#img11,#img-11{\r\n");
      out.write("\theight:850px;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index_include/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index_include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<table id=\"tbl1\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img1\" src=\"display?fileName=jpg5.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img-1\" src=\"display?fileName=COUPLE.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img2\" src=\"display?fileName=jpg2.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img-2\" src=\"display?fileName=PET.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img3\" src=\"display?fileName=gif5.gif\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img4\" src=\"display?fileName=jpg7.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table id=\"tbl2\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img5\" src=\"display?fileName=jpg6.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img-5\" src=\"display?fileName=FAMILY.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img6\" src=\"display?fileName=jpg10.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img7\" src=\"display?fileName=gif1.gif\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img8\" src=\"display?fileName=jpg1.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img-8\" src=\"display?fileName=PROFILE.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img9\" src=\"display?fileName=jpg3.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<table id=\"tbl3\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img10\" src=\"display?fileName=gif2.gif\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img11\" src=\"display?fileName=jpg8.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img-11\" src=\"display?fileName=FRIEND.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<img id=\"img12\" src=\"display?fileName=jpg4.jpg\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<img id=\"img13\" src=\"display?fileName=introduce.jpg\">\r\n");
      out.write("\t\t\t<img id=\"img14\" src=\"display?fileName=introduce1.jpg\">\r\n");
      out.write("\t\t\t<!-- photo_package 출력하기 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">⊙ PACKAGE ⊙</div>\r\n");
      out.write("\t\t\t\t<div id=\"package\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"image\" src=\"display?fileName=package_family6.jpg\" onClick=\"location.href='/package/packageRead?photo_package_code=A1'\">\r\n");
      out.write("\t\t\t\t\t\t\t<br><a href=\"/package/packageRead?photo_package_code=A1\">가족사진</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t190,000\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"image\" src=\"display?fileName=package_couple2.jpg\" onClick=\"location.href='/package/packageRead?photo_package_code=A2'\">\r\n");
      out.write("\t\t\t\t\t\t\t<br><a href=\"/package/packageRead?photo_package_code=A2\">커플사진</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t50,000\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"image\" src=\"display?fileName=package_profile2.jpg\" onClick=\"location.href='/package/packageRead?photo_package_code=B2'\" >\r\n");
      out.write("\t\t\t\t\t\t\t<br><a href=\"/package/packageRead?photo_package_code=B2\">프로필사진</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t28,000\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"image\" src=\"display?fileName=package_pet7.jpg\" onClick=\"location.href='/package/packageRead?photo_package_code=C1'\">\r\n");
      out.write("\t\t\t\t\t\t\t<br><a href=\"/package/packageRead?photo_package_code=C1\">펫사진</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t19,900\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"image\" src=\"display?fileName=package_friend2.jpg\" onClick=\"location.href='/package/packageRead?photo_package_code=B1'\">\r\n");
      out.write("\t\t\t\t\t\t\t<br><a href=\"/package/packageRead?photo_package_code=B1\">우정사진</a><br>\r\n");
      out.write("\t\t\t\t\t\t\t30,000\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- photo_package 출력끝 -->\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index_include/chat.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index_include/top.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index_include/popup.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\".items8\").on(\"click\",function(){\r\n");
      out.write("\t\t\tvar offset = $('.items8').offset(); //선택한 태그의 위치를 반환\r\n");
      out.write("\t            //animate()메서드를 이용해서 선택한 태그의 스크롤 위치를 지정해서 0.4초 동안 부드럽게 해당 위치로 이동함 \r\n");
      out.write("\t        $('html').animate({scrollTop : 3000}, 400);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img14\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/index_include/introduce\";\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t/*read페이지로이동--------------------------------------------------*/\r\n");
      out.write("\t$(\"#img-1\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/couple\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img-5\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/family\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img-2\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/pet\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img-11\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/friend\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img-8\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/profile\";\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#img1\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/couple\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img5\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/family\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img2\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/pet\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img11\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/friend\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img8\").on(\"click\",function(){\r\n");
      out.write("\t\tlocation.href=\"/read/profile\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/*이미지hover-----------------------------------------------------*/\r\n");
      out.write("\t$(\"#img1\").hover(function(){\r\n");
      out.write("\t\t$(\"#img1\").hide();\r\n");
      out.write("\t\t$(\"#img-1\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img1\").on(\"mouseleave\",function(){\r\n");
      out.write("\t\t$(\"#img-1\").hide();\r\n");
      out.write("\t\t$(\"#img1\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img2\").hover(function(){\r\n");
      out.write("\t\t$(\"#img2\").hide();\r\n");
      out.write("\t\t$(\"#img-2\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img2\").on(\"mouseleave\",function(){\r\n");
      out.write("\t\t$(\"#img-2\").hide();\r\n");
      out.write("\t\t$(\"#img2\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img5\").hover(function(){\r\n");
      out.write("\t\t$(\"#img5\").hide();\r\n");
      out.write("\t\t$(\"#img-5\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img5\").on(\"mouseleave\",function(){\r\n");
      out.write("\t\t$(\"#img-5\").hide();\r\n");
      out.write("\t\t$(\"#img5\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img8\").hover(function(){\r\n");
      out.write("\t\t$(\"#img8\").hide();\r\n");
      out.write("\t\t$(\"#img-8\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img8\").on(\"mouseleave\",function(){\r\n");
      out.write("\t\t$(\"#img-8\").hide();\r\n");
      out.write("\t\t$(\"#img8\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#img11\").hover(function(){\r\n");
      out.write("\t\t$(\"#img11\").hide();\r\n");
      out.write("\t\t$(\"#img-11\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#img11\").on(\"mouseleave\",function(){\r\n");
      out.write("\t\t$(\"#img-11\").hide();\r\n");
      out.write("\t\t$(\"#img11\").show();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
