/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-08-06 05:22:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cvs_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<title>24/7</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../home.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#divContent {\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divContent table {\r\n");
      out.write("\tmargin-top: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divPage\" style=\"height:700px\">\r\n");
      out.write("\t\t<div id=\"divCenter\">\r\n");
      out.write("\t\t\t<div id=\"divTop\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t\t<div class=\"dropmenu\">\r\n");
      out.write("\t\t\t\t<ul id=\"dm_ul\">\r\n");
      out.write("\t\t\t\t\t<li><a id=plist href=\"/semiProject/product/list.jsp\">상품리스트</a></li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li>현황관리\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/stock/list.jsp\">재고현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/sell_status/list.jsp\">판매현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/order/list.jsp\">발주현황</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<li>등록관리\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/order/insert.jsp\">발주등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/product/insert.jsp\">상품등록</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<li>이건어때\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/bbs/insert.jsp\">칭찬해요</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=alist href=\"/semiProject/bbs/binsert.jsp\">제안해요</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<img id=\"logo\" src=../images/tfs_logo.JPG>\r\n");
      out.write("\t\t\t<div id=\"divContent\">\r\n");
      out.write("\t\t\t\t<!--여기에 내용출력 시작--------------------#8ABCEE-------- -->\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tstyle=\"text-align: center; margin-top: 100px; background: #2569C9; border: 1px solid #2569C9; border-radius: 10px; width: 330px; height: 330px; margin: auto; margin-top: 100px; margin-bottom: 100px;\">\r\n");
      out.write("\t\t\t\t\t<form name=\"frm\" action=\"cvs_login\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<h1 style=\"color: white;margin-bottom:25px;margin-top:50px\">점주로그인</h1>\r\n");
      out.write("\t\t\t\t\t\t<div style= height:30px;color:white;font-weight:bold>\r\n");
      out.write("\t\t\t\t\t\t\t<span>아이디</span>&nbsp;&nbsp;&nbsp; <span><input type=\"text\" name=\"cvs_id\"  placeholder=\"점주코드 ex)A01\" size=20;></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style= height:30px;color:white;font-weight:bold>\r\n");
      out.write("\t\t\t\t\t\t\t<span>비밀번호</span> <span><input type=\"password\" name=\"pass\" size=20;></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div style= height:50px;margin-top:40px>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" class=\"button\" value=\"LOGIN\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--여기에 내용출력 종료---------------------------- -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"divFoot\" style=\"text-align: center;\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\".dropmenu ul li\").hover(function() {\r\n");
      out.write("\t\t$(this).find(\"ul\").stop().fadeToggle(300);\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$(frm).submit(function(e){\r\n");
      out.write("\t\tvar cvs_id=$(frm.cvs_id).val();\r\n");
      out.write("\t\tvar pass=$(frm.pass).val();\r\n");
      out.write("\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"cvs_login\",\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tdata:{\"cvs_id\":cvs_id,\"pass\":pass},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tif(data.check==0){\r\n");
      out.write("\t\t\t\t\talert(\"id가 존재하지 않습니다!\");\r\n");
      out.write("\t\t\t\t}else if(data.check==1){\r\n");
      out.write("\t\t\t\t\talert(\"id와 비밀번호가 일치하지 않습니다!\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tlocation.href=\"../index.jsp\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
