/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-09-07 05:40:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.index_005finclude;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class popup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js\"></script>\r\n");
      out.write("<title>코로나 예방 수칙</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* CSS */\r\n");
      out.write(".contents {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tmax-width: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contents .title {\r\n");
      out.write("\tmargin: 10px 0;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contents p {\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup:before {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, .5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup .layerBox {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder-radius: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup .layerBox .title {\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tborder-bottom: 1px solid #d9d9d9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup .layerBox .cont {\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup .layerBox p {\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup .layerBox .btnClose {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 30px;\r\n");
      out.write("\tbottom:23px;\r\n");
      out.write("\tpadding: 6px 12px;\r\n");
      out.write("\tcolor: #444;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layerPopup .layerBox .btnTodayHide {\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- layer popup content -->\r\n");
      out.write("\t<div class=\"layerPopup\">\r\n");
      out.write("\t\t<div class=\"layerBox\">\r\n");
      out.write("\t\t\t<h1 class=\"title\">코로나 예방 수칙</h1>\r\n");
      out.write("\t\t\t<div class=\"cont\">\r\n");
      out.write("\t\t\t\t<img src=\"display?fileName=popup.jpg\" width=500 height=500 style=\"margin:0px;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<a href=\"javascript:;\" class=\"btnTodayHide\">오늘 하루 보지 않기</a>\r\n");
      out.write("\t\t\t<button onClick=\"location.href='javascrfipt:;'\" class=\"btnClose\">X</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar $layerPopup = document.querySelector('.layerPopup');\r\n");
      out.write("\tvar $btnLayerPopupClose = document.querySelector('.layerPopup .btnClose');\r\n");
      out.write("\tvar $btnLayerPopupTodayHide = document\r\n");
      out.write("\t\t\t.querySelector('.layerPopup .btnTodayHide');\r\n");
      out.write("\r\n");
      out.write("\t//최초 레이어팝업 노출\r\n");
      out.write("\tlayerPopupShow();\r\n");
      out.write("\r\n");
      out.write("\t//레이어팝업 닫기 버튼 클릭\r\n");
      out.write("\t$btnLayerPopupClose.addEventListener('click', function() {\r\n");
      out.write("\t\tlayerPopupHide(0);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//레이어팝업 오늘 하루 보지 않기 버튼 클릭\r\n");
      out.write("\t$btnLayerPopupTodayHide.addEventListener('click', function() {\r\n");
      out.write("\t\tlayerPopupHide(1);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//레이어팝업 노출\r\n");
      out.write("\tfunction layerPopupShow() {\r\n");
      out.write("\t\tif ($.cookie('testCookie') == undefined) {\r\n");
      out.write("\t\t\t$layerPopup.style.display = 'block'\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//레이어팝업 비노출\r\n");
      out.write("\tfunction layerPopupHide(state) {\r\n");
      out.write("\t\t//닫기버튼 오늘하루보지않기 버튼 무관하계 레이어팝업은 닫는다.\r\n");
      out.write("\t\t$layerPopup.style.display = 'none'\r\n");
      out.write("\r\n");
      out.write("\t\t//오늘하루보지않기 버튼을 누른 경우\r\n");
      out.write("\t\tif (state == 1) {\r\n");
      out.write("\t\t\t//'testCookie' 이름의 쿠키가 있는지 체크한다.\r\n");
      out.write("\t\t\tif ($.cookie('testCookie') == undefined) {\r\n");
      out.write("\t\t\t\t//쿠키가 없는 경우 testCookie 쿠키를 추가\r\n");
      out.write("\t\t\t\t$.cookie('testCookie', 'testCK', {\r\n");
      out.write("\t\t\t\t\texpires : 1\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t/**\r\n");
      out.write("\t\t\t\t    설명 :\r\n");
      out.write("\t\t\t\t    임의로 testCookie라는 이름에 Y라는 값을 넣어주었고,\r\n");
      out.write("\t\t\t\t    expires값으로 1을 주어 1일 후 쿠키가 삭제되도록 하였다.\r\n");
      out.write("\t\t\t\t    path값을 '/'로 주면 해당사이트 모든페이지에서 유효한 쿠키를 생성한다.\r\n");
      out.write("\t\t\t\t    특정페이지에서만 작동하려면 페이지 경로를 작성하면 된다.\r\n");
      out.write("\t\t\t\t **/\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
