/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-09-07 11:00:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.read;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class family_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>방울방울</title>\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("   font-family: '@여기어때 잘난체';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#page {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("\tpadding-bottom:30px;\r\n");
      out.write("\theight: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("   margin-top: none;\r\n");
      out.write("   margin-left: 70px;\r\n");
      out.write("   margin-right: 70px;\r\n");
      out.write("   padding: 30px margin-top: 10px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#family1,#family2,#family3,#family4,#family5{\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#tbl1 {\r\n");
      out.write("   width: 50%;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("   margin: 25px;\r\n");
      out.write("   padding: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("   font-size: 50px;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#imgButton {\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#menu {\r\n");
      out.write("   width: 760px;\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#darken-background {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: 0px;\r\n");
      out.write("   left: 0px;\r\n");
      out.write("   right: 0px;\r\n");
      out.write("   height: 0%;\r\n");
      out.write("   display: none;\r\n");
      out.write("   background: rgba(0, 0, 0, 0.5);\r\n");
      out.write("   z-index: 10000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lightbox {\r\n");
      out.write("   width:1200px;\r\n");
      out.write("   height:900px;\r\n");
      out.write("   margin: 20px auto;\r\n");
      out.write("   padding: 15px;\r\n");
      out.write("   border: 1px solid #333333;\r\n");
      out.write("   border-radius: 5px;\r\n");
      out.write("   background: white;\r\n");
      out.write("   box-shadow: 0px 5px 5px rgba(34, 25, 25, 0.4);\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnClose {\r\n");
      out.write("   border:none;\r\n");
      out.write("   background:white;\r\n");
      out.write("   font-size:50px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#perPage{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("   margin-top:400px;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   border:none;\r\n");
      out.write("   background:white;\r\n");
      out.write("   font-size:60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nextPage{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("   margin-top:400px;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   border:none;\r\n");
      out.write("   background:white;\r\n");
      out.write("   font-size:60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lightbox img{\r\n");
      out.write("\t position: relative;\r\n");
      out.write("\t top:55px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/menu.jsp", out, false);
      out.write("\r\n");
      out.write("   <div id=\"page\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/header.jsp", out, false);
      out.write("\r\n");
      out.write("      <div class=\"title\">⊙ FAMILY ⊙</div>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("         <table id=\"tbl1\">\r\n");
      out.write("            <tr class = \"box\">\r\n");
      out.write("               <td>\r\n");
      out.write("                  <img id=\"family1\" page=1 src=\"../display?fileName=family-1.jpg\" width=500>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <img id=\"family2\" page=2 src=\"../display?fileName=family-2.jpg\" width=500>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class = \"box\">\r\n");
      out.write("               <td>\r\n");
      out.write("                  <img id=\"family3\" page=3 src=\"../display?fileName=family-3.jpg\" width=500>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <img id=\"family4\" page=4 src=\"../display?fileName=family-4.jpg\" width=500>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class = \"box\">\r\n");
      out.write("               <td colspan=2>\r\n");
      out.write("                  <img id=\"family5\" page=5 src=\"../display?fileName=family-5.jpg\" width=1000>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("      <div>\r\n");
      out.write("         <img id=\"imgButton\" src=\"../display?fileName=예약하기.png\" width=300>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!--라이트 박스-->\r\n");
      out.write("   <div id=\"darken-background\">\r\n");
      out.write("      <div id=\"lightbox\">\r\n");
      out.write("         <div style=\"text-align:right; margin-right:10px;\">\r\n");
      out.write("            <button id=\"btnClose\">X</button>\r\n");
      out.write("         </div>\r\n");
      out.write("         <button id=\"perPage\" disabled=\"false\">&lt</button>\r\n");
      out.write("         <img id=\"lightImg\"/>\r\n");
      out.write("         <button id=\"nextPage\" disabled=\"false\">&gt</button>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../reservation/reservation.jsp", out, false);
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/chat.jsp", out, false);
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/top.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var src1=\"../display?fileName=family-\";\r\n");
      out.write("var src2=\".jpg\";\r\n");
      out.write("var page;\r\n");
      out.write("$(\"#imgButton\").on(\"click\",function(){\r\n");
      out.write("    location.href=\"/reservation/calendar\";\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\".box\").on(\"click\", \"img\", function() {\r\n");
      out.write("    var src = $(this).attr(\"src\");\r\n");
      out.write("    page= $(this).attr(\"page\");\r\n");
      out.write("    \r\n");
      out.write("    pageOnOff();\r\n");
      out.write("    \r\n");
      out.write("    $(\"#lightbox img\").attr(\"src\", src1+page+src2);\r\n");
      out.write("    $(\"#lightbox img\").attr(\"page\", page);\r\n");
      out.write("    $(\"#darken-background\").show();\r\n");
      out.write("    var offset = $('.box').offset(); //선택한 태그의 위치를 반환\r\n");
      out.write("    //animate()메서드를 이용해서 선택한 태그의 스크롤 위치를 지정해서 0.4초 동안 부드럽게 해당 위치로 이동함 \r\n");
      out.write("\t$('html').animate({scrollTop : 0}, 400);\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write(" $(\"#btnClose\").on(\"click\", function() {\r\n");
      out.write("    $(\"#darken-background\").hide();\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("$(\"#perPage\").on(\"click\", function(){\r\n");
      out.write(" page = $(\"#lightbox img\").attr(\"page\");\r\n");
      out.write(" page--;\r\n");
      out.write(" var src = src1+page+src2;\r\n");
      out.write(" $(\"#lightbox img\").attr(\"src\", src);\r\n");
      out.write(" $(\"#lightbox img\").attr(\"page\",page);\r\n");
      out.write("\r\n");
      out.write(" pageOnOff();\r\n");
      out.write(" var offset = $('.box').offset();\r\n");
      out.write("\t$('html').animate({scrollTop : 0}, 400);\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write(" $(\"#nextPage\").on(\"click\", function(){\r\n");
      out.write("    page = $(\"#lightbox img\").attr(\"page\");\r\n");
      out.write("    page++;\r\n");
      out.write("    var src = src1+page+src2;\r\n");
      out.write("    $(\"#lightbox img\").attr(\"src\", src);\r\n");
      out.write("    $(\"#lightbox img\").attr(\"page\",page);\r\n");
      out.write("    \r\n");
      out.write("    pageOnOff();\r\n");
      out.write("    var offset = $('.box').offset();\r\n");
      out.write("\t$('html').animate({scrollTop : 0}, 400);\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("function pageOnOff(){\r\n");
      out.write("   if(page==1){\r\n");
      out.write("      $(\"#perPage\").attr(\"disabled\",true);\r\n");
      out.write("      $(\"#nextPage\").attr(\"disabled\",false); \r\n");
      out.write("   }else if(page==5){\r\n");
      out.write("      $(\"#nextPage\").attr(\"disabled\",true);\r\n");
      out.write("      $(\"#perPage\").attr(\"disabled\",false);\r\n");
      out.write("   }else{\r\n");
      out.write("      $(\"#perPage\").attr(\"disabled\",false);\r\n");
      out.write("      $(\"#nextPage\").attr(\"disabled\",false); \r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
