/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-09-07 10:56:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.QnA_005fFAQ;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FAQ_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/data/0625%20semi/semiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FINAL%20LOCAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1592786321749L));
    _jspx_dependants.put("jar:file:/C:/data/0625%20semi/semiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FINAL%20LOCAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>FAQ</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {font-family:'@여기어때 잘난체';}\r\n");
      out.write("#page {\r\n");
      out.write("\tbackground: white; \r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("\theight: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("\tmargin-top:none;\r\n");
      out.write("\tmargin-left:70px;\r\n");
      out.write("\tmargin-right:70px;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth:80%;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title{\r\n");
      out.write("\tfont-size:50px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Q{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tfont-size:50px;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".Qq{\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Qq:hover{\r\n");
      out.write("\tcolor: #e360f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".A{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-left:0%;\r\n");
      out.write("\tfont-size:50px;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".Aa{\r\n");
      out.write("\twidth:80%;\r\n");
      out.write("\theight:hidden;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tbackground:#BDBDBD;\r\n");
      out.write("\tmargin:auto;\r\n");
      out.write("\tpadding:20px;\r\n");
      out.write("\tborder-radius:10px 10px 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("#closeAll{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ask,#ask2,#ask3,#ask4,#ask5,#ask6,#ask7,#ask8,#ask9,#ask10{\r\n");
      out.write("\tmargin:50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#close,#close2,#close3,#close4,#close5,#close6,#close7,#close8,#close9,#close10{\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #e6bbea;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#closeAll button{\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #e6bbea;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#closeAll button:active,#close:active,#close2:active,#close3:active,#close4:active,#close5:active,#close6:active,#close7:active,#close8:active,#close9:active,#close10:active {\r\n");
      out.write("\tbackground: #cca6cf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<div class=\"title\">⊙ FAQ ⊙</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div id=\"closeAll\"><button>전체 닫기</button></div>\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<div id=\"ask\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">회원가입 후에만 예약할 수 있나요??</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">죄송합니다. 저희 방울방울 스튜디오는 회원제로 이용가능한 사이트입니다.<br>\r\n");
      out.write("\t\t\t\t현재 비회원 기능으로는 Q&A작성과 갤러리만 볼 수 있으며,<br>\r\n");
      out.write("\t\t\t\t회원님들의 의견을 충분히 반영하여 비회원 예약이 가능할 수 있도록 노력하겠습니다!<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask2\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">주차장이 따로 있나요? 없다면 스튜디오 근처에 공영주차장을 알 수 있을까요?</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply2\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">죄송합니다. 저희 스튜디오 내의 주차장은 존재하지 않으나 근처 공영주차장이 여러곳이 있으니 확인 후 주차하시면 되겠습니다~<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close2\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask3\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">제가 원하는 컨셉과 비용이 있는데 메뉴 상에는 없는것 같습니다. </span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply3\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">자세한 답변은 카카오톡 오픈채팅 및 전화상담 이용 부탁드립니다.^^<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close3\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask4\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">출장 촬영에 대하여 문의합니다.</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply4\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">출장 촬영은 가능하나 예약된 스케줄을 보고 답변을 드릴 수 있습니다.<br>\r\n");
      out.write("\t\t\t\t스케쥴 및 자세한 비용문의는 카카오톡 오픈 채팅 또는 전화상담 이용 부탁드립니다.^^<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close4\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask5\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">당일날 상품 변경이 가능한가요?</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply5\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">당일 상품 변경은 불가합니다.<br>\r\n");
      out.write("\t\t\t\t패키지 안에 야외촬영이 포함되어 있는 경우 일정을 미루시거나 시간 조정후 촬영 가능하십니다~<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close5\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask6\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">촬영시간은 얼마나 걸리나요?</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply6\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">촬영시간은 정확히 말씀 드릴 수 없으나 패키지에 따라 다른 편이며, <br>\r\n");
      out.write("\t\t\t\t패키지 촬영의 경우 평균 소요시간은 대략 1-2시간 정도 소용될 수 있습니다!(상품,날씨,변수,상황에 따라 다를 수 있습니다.)<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close6\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask7\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">예약 방법은 어떻게 되나요?</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply7\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">저희 방울방울 스튜디오는 더 좋은 서비스와 고객님들의 인생사진을 제공해 드리기 위해 예약제로 운영되고 있습니다.<br>\r\n");
      out.write("\t\t\t\t카카오톡 오픈채팅 또는 해당 사이트 예약 페이지를 이용해 예약 및 문의가 가능하십니다.^^<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close7\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask8\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">상품제작기간은 얼마나 소요되며 어떻게 받나요?</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply8\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">앨범 및 사진의 제작 기간은 약 2주 정도 입니다!<br>\r\n");
      out.write("\t\t\t\t상품은 방울방울 스튜디오에 방문하셔서 제작된 상품의 이상이 없는 지 확인 후 찾아보실수 있습니다.<br>\r\n");
      out.write("\t\t\t\t또한 상품 배송중 파손의 위험이있는 액자의 경우를 제외하고 택배배송 서비스도 이용하실 수 있으며,<br>\r\n");
      out.write("\t\t\t\t증명사진 또는 간단한 사진촬영 후 인쇄된 사진은 촬영후 20분 정도면 바로 찾아보실 수 있습니다!<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close8\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask9\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">방울방울 스튜디오의 휴일 및 영업시간을 알려주세요!</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply9\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">저희 방울방울 스튜디오의 휴일은 매주 화요일이며, 영업시간은 am 9시30분 ~ pm 6시30분까지입니다.<br>\r\n");
      out.write("\t\t\t\t특별한경우 전화 예약을 이용하시어 휴일인 화요일도 예약하실 수 있습니다.<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close9\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ask10\">\r\n");
      out.write("\t\t\t<span class=\"Q\">Q.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Qq\">방울방울 스튜디오 내에서 코스튬 상품을 구매할 수 있나요?</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"reply10\">\r\n");
      out.write("\t\t\t<span class=\"A\">A.</span>\r\n");
      out.write("\t\t\t\t<span class=\"Aa\">죄송합니다. 저희 방울방울 스튜디오에서 COSTUME상품은 촬영내에서 대여만 가능하시며,<br>\r\n");
      out.write("\t\t\t\t구매는 불가 하십니다!<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"close10\">닫기</button></span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/chat.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../index_include/top.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#reply\").hide();\r\n");
      out.write("\t$(\"#reply2\").hide();\r\n");
      out.write("\t$(\"#reply3\").hide();\r\n");
      out.write("\t$(\"#reply4\").hide();\r\n");
      out.write("\t$(\"#reply5\").hide();\r\n");
      out.write("\t$(\"#reply6\").hide();\r\n");
      out.write("\t$(\"#reply7\").hide();\r\n");
      out.write("\t$(\"#reply8\").hide();\r\n");
      out.write("\t$(\"#reply9\").hide();\r\n");
      out.write("\t$(\"#reply10\").hide();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#ask\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask2\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply2\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask3\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply3\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask4\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply4\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask5\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply5\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask6\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply6\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask7\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply7\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask8\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply8\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask9\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply9\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#ask10\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply10\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#close\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close2\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply2\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close3\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply3\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close4\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply4\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close5\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply5\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close6\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply6\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close7\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply7\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close8\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply8\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close9\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply9\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#close10\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply10\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#closeAll button\").on(\"click\", function(){\r\n");
      out.write("\t\t$(\"#reply\").hide();\r\n");
      out.write("\t\t$(\"#reply2\").hide();\r\n");
      out.write("\t\t$(\"#reply3\").hide();\r\n");
      out.write("\t\t$(\"#reply4\").hide();\r\n");
      out.write("\t\t$(\"#reply5\").hide();\r\n");
      out.write("\t\t$(\"#reply6\").hide();\r\n");
      out.write("\t\t$(\"#reply7\").hide();\r\n");
      out.write("\t\t$(\"#reply8\").hide();\r\n");
      out.write("\t\t$(\"#reply9\").hide();\r\n");
      out.write("\t\t$(\"#reply10\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
