/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-09-07 10:23:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class costumechart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/data/0625%20semi/semiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FINAL%20LOCAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1592786321749L));
    _jspx_dependants.put("jar:file:/C:/data/0625%20semi/semiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FINAL%20LOCAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <title>COSTUME CHART</title>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("   <style>\r\n");
      out.write("select{\r\n");
      out.write("   height: 30px;\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#COSTUME{\r\n");
      out.write("   color:#e360f2;\r\n");
      out.write("   font-size: 50px;\r\n");
      out.write("   text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;\r\n");
      out.write("   margin:20px;\r\n");
      out.write("}\r\n");
      out.write("#chart_div3,#chart_div4{\r\n");
      out.write("   margin:auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cbtnMonth{\r\n");
      out.write("   width: 80px;\r\n");
      out.write("   height: 30px;\r\n");
      out.write("   font-size: 15px;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   background: #e6bbea;\r\n");
      out.write("   color: white;\r\n");
      out.write("   border: none;\r\n");
      out.write("   border-radius: 3px 3px 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cbtnMonth:active {\r\n");
      out.write("   background: #cca6cf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      <div id=\"COSTUME\">COSTUME CHART</div>\r\n");
      out.write("      <select id=\"cselYear\" style=\"height: 25px;\">\r\n");
      out.write("         <option value=\"2015\">2015년</option>\r\n");
      out.write("         <option value=\"2016\">2016년</option>\r\n");
      out.write("         <option value=\"2017\">2017년</option>\r\n");
      out.write("         <option value=\"2018\">2018년</option>\r\n");
      out.write("         <option value=\"2019\">2019년</option>\r\n");
      out.write("         <option value=\"2020\" selected>2020년</option>\r\n");
      out.write("         <option value=\"2021\">2021년</option>\r\n");
      out.write("         <option value=\"2022\">2022년</option>\r\n");
      out.write("         <option value=\"2023\">2023년</option>\r\n");
      out.write("         <option value=\"2024\">2024년</option>\r\n");
      out.write("         <option value=\"2025\">2025년</option>\r\n");
      out.write("         <option value=\"2026\">2026년</option>\r\n");
      out.write("         <option value=\"2027\">2027년</option>\r\n");
      out.write("         <option value=\"2028\">2028년</option>\r\n");
      out.write("         <option value=\"2029\">2029년</option>\r\n");
      out.write("         <option value=\"2030\">2030년</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <select id=\"cselMonth\">\r\n");
      out.write("         <option value=\"1\">1월</option>\r\n");
      out.write("         <option value=\"2\">2월</option>\r\n");
      out.write("         <option value=\"3\">3월</option>\r\n");
      out.write("         <option value=\"4\">4월</option>\r\n");
      out.write("         <option value=\"5\">5월</option>\r\n");
      out.write("         <option value=\"6\">6월</option>\r\n");
      out.write("         <option value=\"7\">7월</option>\r\n");
      out.write("         <option value=\"8\" selected>8월</option>\r\n");
      out.write("         <option value=\"9\">9월</option>\r\n");
      out.write("         <option value=\"10\">10월</option>\r\n");
      out.write("         <option value=\"11\">11월</option>\r\n");
      out.write("         <option value=\"12\">12월</option>\r\n");
      out.write("      </select>\r\n");
      out.write("      <button class=\"cbtnMonth\">SHOW</button>\r\n");
      out.write("      <div id=\"chart_div3\" style=\"width: 600px; height: 500px;\"></div>\r\n");
      out.write("      <div id=\"chart_div4\" style=\"width: 600px; height: 500px;\"></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var varTitle;\r\n");
      out.write("\r\n");
      out.write("$(\".cbtnMonth\").click(function(){\r\n");
      out.write("   var month=$(\"#cselMonth option:checked\").val();\r\n");
      out.write("   var year=$(\"#cselYear option:checked\").val();\r\n");
      out.write("   varTitle=$(\"#selChart option:checked\").text();\r\n");
      out.write("   changeChart();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("changeChart();\r\n");
      out.write("\r\n");
      out.write("function changeChart(){\r\n");
      out.write("    google.charts.load('current', {'packages':['corechart']});\r\n");
      out.write("    google.charts.setOnLoadCallback(drawVisualization);\r\n");
      out.write("    function drawVisualization() { \r\n");
      out.write("       \r\n");
      out.write("       var month=$(\"#cselMonth option:checked\").val();\r\n");
      out.write("       var year=$(\"#cselYear option:checked\").val();\r\n");
      out.write("       \r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type:\"get\",\r\n");
      out.write("            url:\"/costumechartt\",\r\n");
      out.write("            data:{\"month\":month, \"year\":year},\r\n");
      out.write("            dataType:\"json\",\r\n");
      out.write("          \r\n");
      out.write("            success:function(result){\r\n");
      out.write("              //테스트용  var result=[['과목명','점수'],['자료구조',90],['데이타베이스',80],['자바',99],['김치전',52],['파전',0]];\r\n");
      out.write("                /* 데이터 셋팅 */\r\n");
      out.write("                var data = google.visualization.arrayToDataTable(result);\r\n");
      out.write("\r\n");
      out.write("                /* 옵션 셋팅 */\r\n");
      out.write("                var options = {\r\n");
      out.write("                   title : varTitle,\r\n");
      out.write("                    seriesType: 'bars',\r\n");
      out.write("                    \r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                /* 차트 그리기 */\r\n");
      out.write("                var chart = new google.visualization.ComboChart(document.getElementById('chart_div3'));\r\n");
      out.write("                chart.draw(data, options);\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type:\"get\",\r\n");
      out.write("            url:\"/costumechartt2\",\r\n");
      out.write("            dataType:\"json\",\r\n");
      out.write("            data:{\"month\":month, \"year\":year},\r\n");
      out.write("            success:function(result){\r\n");
      out.write("              //테스트용  var result=[['과목명','점수'],['자료구조',90],['데이타베이스',80],['자바',99],['김치전',52],['파전',0]];\r\n");
      out.write("                /* 데이터 셋팅 */\r\n");
      out.write("                var data = google.visualization.arrayToDataTable(result);\r\n");
      out.write("\r\n");
      out.write("                /* 옵션 셋팅 */\r\n");
      out.write("                var options = {\r\n");
      out.write("                   title : varTitle,\r\n");
      out.write("                    seriesType: 'line'\r\n");
      out.write("                   \r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                /* 차트 그리기 */\r\n");
      out.write("                var chart = new google.visualization.ComboChart(document.getElementById('chart_div4'));\r\n");
      out.write("                chart.draw(data, options);\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
