/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-09-07 07:20:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>LOGIN</title>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: 'Comic Sans MS';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 50px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".or {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#id input, #pw input {\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn, #id, #pw {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#divLoginPage {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnLogin, #btnSignup {\r\n");
      out.write("\twidth: 335px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tfont-size: 30px;\r\n");
      out.write("\tmargin: 2px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: #e6bbea;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btnLogin:active, #btnSignup:active {\r\n");
      out.write("\tbackground: #cca6cf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".kakao, .naver {\r\n");
      out.write("\tfloat: center;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checks{\r\n");
      out.write("\tmargin-left: 90px;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checks {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checks input[type=\"checkbox\"] { /* 실제 체크박스는 화면에서 숨김 */\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: -1px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tclip: rect(0, 0, 0, 0);\r\n");
      out.write("\tborder: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checks input[type=\"checkbox\"]+label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\t-ms-user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checks input[type=\"checkbox\"]+label:before { /* 가짜 체크박스 */\r\n");
      out.write("\tcontent: ' ';\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 21px; /* 체크박스의 너비를 지정 */\r\n");
      out.write("\theight: 21px; /* 체크박스의 높이를 지정 */\r\n");
      out.write("\tline-height: 21px; /* 세로정렬을 위해 높이값과 일치 */\r\n");
      out.write("\tmargin: -2px 8px 0 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tbackground: #fafafa;\r\n");
      out.write("\tborder: 1px solid #cacece;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tbox-shadow: 0px 1px 2px rgba(0, 0, 0, 0.05), inset 0px -15px 10px -12px\r\n");
      out.write("\t\trgba(0, 0, 0, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checks input[type=\"checkbox\"]+label:active:before, .checks input[type=\"checkbox\"]:checked+label:active:before\r\n");
      out.write("\t{\r\n");
      out.write("\tbox-shadow: 0 1px 2px rgba(0, 0, 0, 0.05), inset 0px 1px 3px\r\n");
      out.write("\t\trgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".checks input[type=\"checkbox\"]:checked+label:before { /* 체크박스를 체크했을때 */\r\n");
      out.write("\tcontent: '\\2714'; /* 체크표시 유니코드 사용 */\r\n");
      out.write("\tcolor: #99a1a7;\r\n");
      out.write("\ttext-shadow: 1px 1px #fff;\r\n");
      out.write("\tbackground: #e9ecee;\r\n");
      out.write("\tborder-color: #adb8c0;\r\n");
      out.write("\tbox-shadow: 0px 1px 2px rgba(0, 0, 0, 0.05), inset 0px -15px 10px -12px\r\n");
      out.write("\t\trgba(0, 0, 0, 0.05), inset 15px 10px -12px rgba(255, 255, 255, 0.1);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"divLoginPage\">\r\n");
      out.write("\t\t<br><div class=\"title\"><b>LOGIN</b></div><br>\r\n");
      out.write("\t\t<div id=\"id\"><input type=\"text\" size=40 id=\"users_id\" placeholder=\"　　ID\" maxlength=\"20\"/></div><br>\r\n");
      out.write("\t\t<div id=\"pw\"><input type=\"password\" size=40 id=\"users_pass\" placeholder=\"　　PASSWORD\" maxlength=\"20\"/></div>\r\n");
      out.write("\t\t<div class=\"checks\"><input type=\"checkbox\" id=\"ex_chk\"> <label for=\"ex_chk\">로그인상태유지</label></div><br>\r\n");
      out.write("\t\t<div class=\"btn\"><input type=\"button\" id=\"btnLogin\" value=\"LOGIN\"/></div>\r\n");
      out.write("\t\t<div class=\"btn\"><input type=\"button\" id=\"btnSignup\" value=\"SIGN UP\"/></div>\r\n");
      out.write("\t\t<div class=\"or\">or</div>\r\n");
      out.write("\t\t<div class=\"or\">\r\n");
      out.write("\t\t\t<a href=\"https://kauth.kakao.com/oauth/authorize?client_id=46437f58302b5ad35f92bcb713a26e08&redirect_uri=http://localhost:8088/kakaoLogin&response_type=code\">\r\n");
      out.write("\t\t\t\t<img class=\"kakao\" src=\"../display?fileName=kakao.png\" width=336>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"or\">\r\n");
      out.write("\t\t\t<!-- 네이버아이디로로그인 버튼 노출 영역 -->\r\n");
      out.write("\t\t\t<div id=\"naver_id_login\"></div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t<!-- //네이버아이디로로그인 버튼 노출 영역 -->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\tvar naver_id_login = new naver_id_login(\"bkD4xjtArMlE7W11ZuTX\", \"http://localhost:8088/naverlogin\");\r\n");
      out.write("\t\t\t\tvar state = naver_id_login.getUniqState();\r\n");
      out.write("\t\t\t\tnaver_id_login.setButton(\"green\", 5, 72);\r\n");
      out.write("\t\t\t\tnaver_id_login.setDomain(\"http://localhost:8088/index\");\r\n");
      out.write("\t\t\t\tnaver_id_login.setState(state);\r\n");
      out.write("\t\t\t\tnaver_id_login.init_naver_id_login();\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar birthdayPointChk=false;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnSignup\").on(\"click\",function(){\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t\tvar options = 'width=500, height=1000, top=30, left=30, resizable=no, scrollbars=no, location=no';\r\n");
      out.write("\t\twindow.open('/user/signup', 'SIGN UP', options);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getCookie(name) {\r\n");
      out.write("  \t\tvar value = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');\r\n");
      out.write("  \t\treturn value? value[2] : null;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar a=getCookie('birthdayPointChk');\r\n");
      out.write("\tvar b=getCookie('users_idChk');\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btnLogin\").on(\"click\",function(){\r\n");
      out.write("      var users_id=$(\"#users_id\").val();\r\n");
      out.write("      var users_pass=$(\"#users_pass\").val();\r\n");
      out.write("      var ex_chk=$(\"#ex_chk\").is(\":checked\")==true;\r\n");
      out.write("      \r\n");
      out.write("      if(a!=null && users_id==b){\r\n");
      out.write("  \t\tbirthdayPointChk=a;\r\n");
      out.write("  \t  }\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type:\"post\",\r\n");
      out.write("         url:\"/user/login\",\r\n");
      out.write("         data:{\"users_id\":users_id, \"users_pass\":users_pass, \"ex_chk\":ex_chk, \"birthdayPointChk\":birthdayPointChk},\r\n");
      out.write("         success:function(data){\r\n");
      out.write("        \t if(data==0){\r\n");
      out.write("                 alert(\"존재하지 않는 아이디입니다.\");\r\n");
      out.write("              }else if(data==1){\r\n");
      out.write("                 alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("              }else if(data==3){\r\n");
      out.write("                 alert(\"탈퇴한 회원입니다.\");\r\n");
      out.write("              }else if(data==4){\r\n");
      out.write("                 alert(\"블랙리스트 처리된 회원입니다.\");\r\n");
      out.write("              }else{\r\n");
      out.write("                 window.close();\r\n");
      out.write("                 opener.parent.location.reload();\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("\t$(\"#users_pass\").keydown(function(key){\r\n");
      out.write("\t      if(key.keyCode==13) {\r\n");
      out.write("\t         $(\"#btnLogin\").click();\r\n");
      out.write("\t      }\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
